using Microsoft.EntityFrameworkCore;
using RewardStart.Core.Models;
using System.Reflection;

namespace RewardStart.Core;

public class RewardStartDbContext : DbContext
{
    public RewardStartDbContext()
    {
        var folder = Environment.SpecialFolder.LocalApplicationData;
        var path = Environment.GetFolderPath(folder);
        DBPath = Path.Combine(path, "RewardStar.db");
    }

    public string DBPath { get; }

    public DbSet<Activity> Activities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        =>
            optionsBuilder.UseSqlite($"Data Source={DBPath}")
                .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking) // Default not tracking the changes in the objects generated by EF.
                //.UseLazyLoadingProxies() // Configure Lazy Loads
                .LogTo(Console.WriteLine)
                // The two bellow, do not allow in production, just for debugging and educational purposes
                //.EnableSensitiveDataLogging() 
                .EnableDetailedErrors();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
    }
}