using Microsoft.EntityFrameworkCore;
using RewardStart.Core.Models;
using System.Reflection;

namespace RewardStart.Core;

public enum DatabaseProvider
{
    SQLite,
    PostgreSQL
}

public class RewardStartDbContext : DbContext
{
    public RewardStartDbContext()
    {
        // Check if PostgreSQL should be used
        DatabaseUrl = Environment.GetEnvironmentVariable("DATABASE_URL");

        if (!string.IsNullOrEmpty(DatabaseUrl))
            Provider = DatabaseProvider.PostgreSQL;
        else
        {
            Provider = DatabaseProvider.SQLite;

            // For SQLite: Support both Docker (via environment variable) and local development
            var dbPath = Environment.GetEnvironmentVariable("DB_PATH");
            if (!string.IsNullOrEmpty(dbPath))
                DbPath = dbPath;
            else
            {
                var folder = Environment.SpecialFolder.LocalApplicationData;
                var path = Environment.GetFolderPath(folder);
                DbPath = Path.Combine(path, "RewardStar.db");
            }
        }
    }

    public string? DbPath { get; }
    public string? DatabaseUrl { get; }
    public DatabaseProvider Provider { get; }

    public DbSet<Activity> Activities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Configure database provider
        switch (Provider)
        {
            case DatabaseProvider.PostgreSQL:
                optionsBuilder.UseNpgsql(DatabaseUrl);
                break;

            case DatabaseProvider.SQLite:
                optionsBuilder.UseSqlite($"Data Source={DbPath}");
                break;
        }

        // Apply common configuration for all providers
        optionsBuilder
            .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking) // Default not tracking the changes in the objects generated by EF.
            //.UseLazyLoadingProxies() // Configure Lazy Loads
            .LogTo(Console.WriteLine)
            // The two below, do not allow in production, just for debugging and educational purposes
            //.EnableSensitiveDataLogging()
            .EnableDetailedErrors();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
    }
}