using Microsoft.EntityFrameworkCore;
using RewardStar.Core.Models;
using System.Reflection;

namespace RewardStar.Core;

public enum DatabaseProvider
{
    SQLite,
    PostgreSQL
}

public class RewardStarDbContext : DbContext
{
    public RewardStarDbContext()
    {
        // Check if PostgreSQL should be used
        DatabaseUrl = Environment.GetEnvironmentVariable("DATABASE_URL");

        if (!string.IsNullOrEmpty(DatabaseUrl))
            Provider = DatabaseProvider.PostgreSQL;
        else
        {
            Provider = DatabaseProvider.SQLite;

            // For SQLite: Support both Docker (via environment variable) and local development
            var dbPath = Environment.GetEnvironmentVariable("DB_PATH");
            if (!string.IsNullOrEmpty(dbPath))
                DbPath = dbPath;
            else
            {
                var folder = Environment.SpecialFolder.LocalApplicationData;
                var path = Environment.GetFolderPath(folder);
                DbPath = Path.Combine(path, "RewardStar.db");
            }
        }
    }

    public string? DbPath { get; }
    public string? DatabaseUrl { get; }
    public DatabaseProvider Provider { get; }

    public DbSet<Activity> Activities { get; set; }
    public DbSet<User> Users { get; set; }
    public DbSet<GameCompletion> GameCompletions { get; set; }
    public DbSet<GameState> GameStates { get; set; }
    public DbSet<RewardClaim> RewardClaims { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Configure database provider
        switch (Provider)
        {
            case DatabaseProvider.PostgreSQL:
                optionsBuilder.UseNpgsql(DatabaseUrl);
                break;

            case DatabaseProvider.SQLite:
                optionsBuilder.UseSqlite($"Data Source={DbPath}");
                break;
        }

        // Apply common configuration for all providers
        optionsBuilder
            .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking) // Default not tracking the changes in the objects generated by EF.
            //.UseLazyLoadingProxies() // Configure Lazy Loads
            .LogTo(Console.WriteLine)
            // The two below, do not allow in production, just for debugging and educational purposes
            //.EnableSensitiveDataLogging()
            .EnableDetailedErrors();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());

        // Configure DateTime handling for PostgreSQL
        if (Provider == DatabaseProvider.PostgreSQL)
        {
            // Convert all DateTime properties to UTC
            foreach (var entityType in modelBuilder.Model.GetEntityTypes())
            {
                foreach (var property in entityType.GetProperties())
                {
                    if (property.ClrType == typeof(DateTime) || property.ClrType == typeof(DateTime?))
                    {
                        property.SetValueConverter(
                            new Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<DateTime, DateTime>(
                                v => v.Kind == DateTimeKind.Unspecified ? DateTime.SpecifyKind(v, DateTimeKind.Utc) : v.ToUniversalTime(),
                                v => DateTime.SpecifyKind(v, DateTimeKind.Utc)
                            )
                        );
                    }
                }
            }
        }
    }

    public override int SaveChanges()
    {
        ConvertDateTimesToUtc();
        return base.SaveChanges();
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        ConvertDateTimesToUtc();
        return base.SaveChangesAsync(cancellationToken);
    }

    private void ConvertDateTimesToUtc()
    {
        foreach (var entry in ChangeTracker.Entries())
        {
            foreach (var property in entry.Properties)
            {
                if (property.CurrentValue is DateTime dateTime)
                {
                    if (dateTime.Kind == DateTimeKind.Unspecified)
                        property.CurrentValue = DateTime.SpecifyKind(dateTime, DateTimeKind.Utc);
                    else if (dateTime.Kind == DateTimeKind.Local)
                        property.CurrentValue = dateTime.ToUniversalTime();
                }
            }
        }
    }
}